name: Pull Request Form
description: Make a pull request for an existing issue
title: "['Improve existing content']: "
labels:
  - content
body:
  # Thank you for contributing to this project! You must fill out the information below before we can review this pull request.
  # By explaining why you're making a change (or linking to a pull request) and what changes you've made, we can triage your pull request to the best possible team for review.
  # See our [CONTRIBUTING.md](/main/CONTRIBUTING.md) for information how to contribute.
  # For changes to content in [site policy](https://github.com/github/docs/tree/main/content/github/site-policy), see the [CONTRIBUTING guide in the site-policy repo](https://github.com/github/site-policy/blob/main/CONTRIBUTING.md).
  # We cannot accept changes to our translated content right now. See the [contributing.md](/main/CONTRIBUTING.md#earth_asia-translations) for more information.
  # We cannot accept changes to our translated content right now. See the [contributing.md](/main/CONTRIBUTING.md#earth_asia-translations) for more information.
  # Thanks again!

  - type: input
    attributes:
      label: Why?
      # If there's an existing issue for your change, please link to it.
      # If there's _not_ an existing issue, please open one first to make it more likely that this update will be accepted: https://github.com/github/docs/issues/new/choose.
      placeholder: |
        Closes [issue link]
    validations:
      required: true

  - type: textarea
    attributes:
      label: What's being changed?
      placeholder: |
        - Share artifacts of the changes, be they code snippets, GIFs or screenshots; whatever shares the most context.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: I have reviewed my changes in staging.
      description: Look for the latest deployment event in your pull request's timeline, then click **View deployment**
      validations:
        required: false

  - type: checkboxes
    attributes:
      label: Check the following
      options:
        - label: I have reviewed my changes in staging (look for the latest deployment event in your pull request's timeline, then click **View deployment**).
          required: true
