---
name: Target Date Update
description: Target date update
body:
- type: input
  attributes:
    label: Target completion date
    placeholder: With context if the target completion date has changed
    format: text
- type: input
  attributes:
    label: 'Attribution'
    value: '_created with :heart: by typing_ `/status`'
    format: text
