name: Improve existing content
description: Make a suggestion to improve the content in an existing article
title: '[What I really want the title to be]'
labels:
  - content
body:
  - type: markdown
    attributes:
      value: |
        **HUBBERS BEWARE! THE GITHUB/DOCS REPO IS PUBLIC TO THE ENTIRE INTERNET. OPEN AN ISSUE IN GITHUB/DOCS-CONTENT INSTEAD.**
        For questions, ask in [Discussions](https://github.com/github/docs/discussions)
        Before you file an issue read the
        - [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
        - [Contributing guide](https://github.com/github/docs/blob/main/CONTRIBUTING.md)

  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I read and agree to the Code of Conduct
          required: true

  - type: markdown
    attributes:
      value: Check to make sure someone hasn't already opened a similar [issue](https://github.com/github/docs/issues)

  - type: textarea
    attributes:
      label: What article on docs.github.com is affected?
      description: |
        Please link to the article you'd like to see updated
    validations:
      required: true

  - type: textarea
    attributes:
      label: What part(s) of the article would you like to see updated?
      description: |
        - Give as much detail as you can to help us understand the change you want to see. 
        - Why should the docs be changed? What use cases does it support? 
        - What is the expected outcome?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional information
      description: |
        Add any other context or screenshots about the feature request here.
    validations:
      required: false
