name: Algolia Sync Single English Index

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - unlocked

# This workflow requires a label in the format `sync-english-index-for-<PLAN@RELEASE>`
jobs:
  updateIndices:
    name: Update English index for single version based on a label's version
    if: github.repository == 'github/docs-internal'
    runs-on: ubuntu-latest
    steps:
      - name: Get version from label if present
        id: getVersion
        run: $GITHUB_WORKSPACE/.github/actions-scripts/enterprise-algolia-label.js
      - if: ${{ steps.getVersion.outputs.versionToSync }}
        name: checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - if: ${{ steps.getVersion.outputs.versionToSync }}
        uses: actions/setup-node@56899e050abffc08c2b3b61f3ec6a79a9dc3223d
        with:
          node-version: 14.x
      - if: ${{ steps.getVersion.outputs.versionToSync }}
        name: cache node modules
        uses: actions/cache@0781355a23dac32fd3bac414512f4b903437991a
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - if: ${{ steps.getVersion.outputs.versionToSync }}
        name: npm ci
        run: npm ci
      - if: ${{ steps.getVersion.outputs.versionToSync }}
        name: Sync English index for single version
        env:
          VERSION: ${{ steps.getVersion.outputs.versionToSync }}
          LANGUAGE: 'en'
          ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run sync-search
