name: Update content in branch

# **What it does**: Runs special one-time scripts to update content files in a branch. This workflow is triggered from a slash command.
# **Why we have it**: To help mitigate conflicts due to a widespread content update.
# **Who does it impact**: Hubbers with open docs-internal branches that touch content files.

on:
  repository_dispatch:
    types: update_content_in_branch

jobs:
  update_content_in_branch:
    if: github.repository == 'github/docs-internal'
    runs-on: ubuntu-latest
    steps:
      - name: npm ci
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        run: npm ci

      - name: npm run build
        run: npm run build

      - name: Run scripts
        run: |
          script/content-migrations/remove-map-topics.js && script/content-migrations/update-tocs.js

      # This adds, commits, and pushes the changes to the branch
      - name: Check in updated files
        uses: EndBug/add-and-commit@b3c7c1e078a023d75fb0bd326e02962575ce0519
        with:
          # The message for the commit
          message: 'Used slash command to run script/content-migrations/remove-map-topics.js && script/content-migrations/update-tocs.js'
